/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	tektonv1alpha1 "github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1"


	tektonv1alpha1client "github.com/tektoncd/pipeline/pkg/client/resource/clientset/versioned/typed/resource/v1alpha1"
)

// PipelineResourcesClusterGetter has a method to return a PipelineResourceClusterInterface.
// A group's cluster client should implement this interface.
type PipelineResourcesClusterGetter interface {
	PipelineResources() PipelineResourceClusterInterface
}

// PipelineResourceClusterInterface can operate on PipelineResources across all clusters,
// or scope down to one cluster and return a PipelineResourcesNamespacer.
type PipelineResourceClusterInterface interface {
	Cluster(logicalcluster.Name) PipelineResourcesNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*tektonv1alpha1.PipelineResourceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type pipelineResourcesClusterInterface struct {
	clientCache kcpclient.Cache[*tektonv1alpha1client.TektonV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *pipelineResourcesClusterInterface) Cluster(name logicalcluster.Name) PipelineResourcesNamespacer {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &pipelineResourcesNamespacer{clientCache: c.clientCache, name: name}
}


// List returns the entire collection of all PipelineResources across all clusters. 
func (c *pipelineResourcesClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*tektonv1alpha1.PipelineResourceList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).PipelineResources(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all PipelineResources across all clusters.
func (c *pipelineResourcesClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).PipelineResources(metav1.NamespaceAll).Watch(ctx, opts)
}
// PipelineResourcesNamespacer can scope to objects within a namespace, returning a tektonv1alpha1client.PipelineResourceInterface.
type PipelineResourcesNamespacer interface {
	Namespace(string) tektonv1alpha1client.PipelineResourceInterface
}

type pipelineResourcesNamespacer struct {
	clientCache kcpclient.Cache[*tektonv1alpha1client.TektonV1alpha1Client]
	name logicalcluster.Name
}

func (n *pipelineResourcesNamespacer) Namespace(namespace string) tektonv1alpha1client.PipelineResourceInterface {
	return n.clientCache.ClusterOrDie(n.name).PipelineResources(namespace)
}
