/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"net/http"

	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"

	"k8s.io/client-go/rest"

	tektonv1beta1 "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/typed/pipeline/v1beta1"
)

type TektonV1beta1ClusterInterface interface {
	TektonV1beta1ClusterScoper
	ClusterTasksClusterGetter
	CustomRunsClusterGetter
	PipelinesClusterGetter
	PipelineRunsClusterGetter
	TasksClusterGetter
	TaskRunsClusterGetter
}

type TektonV1beta1ClusterScoper interface {
	Cluster(logicalcluster.Name) tektonv1beta1.TektonV1beta1Interface
}

type TektonV1beta1ClusterClient struct {
	clientCache kcpclient.Cache[*tektonv1beta1.TektonV1beta1Client]
}

func (c *TektonV1beta1ClusterClient) Cluster(name logicalcluster.Name) tektonv1beta1.TektonV1beta1Interface {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return c.clientCache.ClusterOrDie(name)
}


func (c *TektonV1beta1ClusterClient) ClusterTasks() ClusterTaskClusterInterface {
	return &clusterTasksClusterInterface{clientCache: c.clientCache}
}

func (c *TektonV1beta1ClusterClient) CustomRuns() CustomRunClusterInterface {
	return &customRunsClusterInterface{clientCache: c.clientCache}
}

func (c *TektonV1beta1ClusterClient) Pipelines() PipelineClusterInterface {
	return &pipelinesClusterInterface{clientCache: c.clientCache}
}

func (c *TektonV1beta1ClusterClient) PipelineRuns() PipelineRunClusterInterface {
	return &pipelineRunsClusterInterface{clientCache: c.clientCache}
}

func (c *TektonV1beta1ClusterClient) Tasks() TaskClusterInterface {
	return &tasksClusterInterface{clientCache: c.clientCache}
}

func (c *TektonV1beta1ClusterClient) TaskRuns() TaskRunClusterInterface {
	return &taskRunsClusterInterface{clientCache: c.clientCache}
}
// NewForConfig creates a new TektonV1beta1ClusterClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*TektonV1beta1ClusterClient, error) {
	client, err := rest.HTTPClientFor(c)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(c, client)
}

// NewForConfigAndClient creates a new TektonV1beta1ClusterClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*TektonV1beta1ClusterClient, error) {
	cache := kcpclient.NewCache(c, h, &kcpclient.Constructor[*tektonv1beta1.TektonV1beta1Client]{
		NewForConfigAndClient: tektonv1beta1.NewForConfigAndClient,
	})
	if _, err := cache.Cluster(logicalcluster.New("root")); err != nil {
		return nil, err
	}
	return &TektonV1beta1ClusterClient{clientCache: cache}, nil
}

// NewForConfigOrDie creates a new TektonV1beta1ClusterClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *TektonV1beta1ClusterClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}
