/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	kcpcache "github.com/kcp-dev/apimachinery/pkg/cache"	
	"github.com/kcp-dev/logicalcluster/v2"
	
	"k8s.io/client-go/tools/cache"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/api/errors"
	
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	tektonv1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	tektonv1listers "github.com/tektoncd/pipeline/pkg/client/listers/pipeline/v1"
	)

// TaskRunClusterLister can list TaskRuns across all workspaces, or scope down to a TaskRunLister for one workspace.
type TaskRunClusterLister interface {
	List(selector labels.Selector) (ret []*tektonv1.TaskRun, err error)
Cluster(cluster logicalcluster.Name)tektonv1listers.TaskRunLister
}

type taskRunClusterLister struct {
	indexer cache.Indexer
}

// NewTaskRunClusterLister returns a new TaskRunClusterLister.
func NewTaskRunClusterLister(indexer cache.Indexer) *taskRunClusterLister {
	return &taskRunClusterLister{indexer: indexer}
}

// List lists all TaskRuns in the indexer across all workspaces.
func (s *taskRunClusterLister) List(selector labels.Selector) (ret []*tektonv1.TaskRun, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*tektonv1.TaskRun))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get TaskRuns.
func (s *taskRunClusterLister) Cluster(cluster logicalcluster.Name)tektonv1listers.TaskRunLister {
return &taskRunLister{indexer: s.indexer, cluster: cluster}
}

// taskRunLister implements the tektonv1listers.TaskRunLister interface.
type taskRunLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all TaskRuns in the indexer for a workspace.
func (s *taskRunLister) List(selector labels.Selector) (ret []*tektonv1.TaskRun, err error) {
	selectAll := selector == nil || selector.Empty()

	list, err := s.indexer.ByIndex(kcpcache.ClusterIndexName, kcpcache.ClusterIndexKey(s.cluster))
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*tektonv1.TaskRun)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// TaskRuns returns an object that can list and get TaskRuns in one namespace.
func (s *taskRunLister) TaskRuns(namespace string) tektonv1listers.TaskRunNamespaceLister {
return &taskRunNamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// taskRunNamespaceLister implements the tektonv1listers.TaskRunNamespaceLister interface.
type taskRunNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all TaskRuns in the indexer for a given workspace and namespace.
func (s *taskRunNamespaceLister) List(selector labels.Selector) (ret []*tektonv1.TaskRun, err error) {
	selectAll := selector == nil || selector.Empty()

	var list []interface{}
	if s.namespace == metav1.NamespaceAll {
		list, err = s.indexer.ByIndex(kcpcache.ClusterIndexName, kcpcache.ClusterIndexKey(s.cluster))
	} else {
		list, err = s.indexer.ByIndex(kcpcache.ClusterAndNamespaceIndexName, kcpcache.ClusterAndNamespaceIndexKey(s.cluster, s.namespace))
	}
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*tektonv1.TaskRun)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the TaskRun from the indexer for a given workspace, namespace and name.
func (s *taskRunNamespaceLister) Get(name string) (*tektonv1.TaskRun, error) {
	key := kcpcache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tektonv1.Resource("TaskRun"), name)
	}
	return obj.(*tektonv1.TaskRun), nil
}
