/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v2"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	tektonv1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"

	"k8s.io/apimachinery/pkg/watch"

	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/types"

	kcptektonv1 "github.com/tektoncd/pipeline/pkg/client/cluster/clientset/typed/tekton/v1"

	tektonv1client "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/typed/pipeline/v1"
)

var tasksResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1", Resource: "tasks"}
var tasksKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1", Kind: "Task"}

type tasksClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *tasksClusterClient) Cluster(cluster logicalcluster.Name) kcptektonv1.TasksNamespacer {
	if cluster == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &tasksNamespacer{Fake: c.Fake, Cluster: cluster}
}


// List takes label and field selectors, and returns the list of Tasks that match those selectors across all clusters.
func (c *tasksClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*tektonv1.TaskList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(tasksResource, tasksKind, logicalcluster.Wildcard, metav1.NamespaceAll, opts), &tektonv1.TaskList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tektonv1.TaskList{ListMeta: obj.(*tektonv1.TaskList).ListMeta}
	for _, item := range obj.(*tektonv1.TaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested Tasks across all clusters.
func (c *tasksClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(tasksResource, logicalcluster.Wildcard, metav1.NamespaceAll, opts))
}
type tasksNamespacer struct {
	*kcptesting.Fake
	Cluster logicalcluster.Name
}

func (n *tasksNamespacer) Namespace(namespace string) tektonv1client.TaskInterface {
	return &tasksClient{Fake: n.Fake, Cluster: n.Cluster, Namespace: namespace}
}
type tasksClient struct {
	*kcptesting.Fake
	Cluster logicalcluster.Name
	Namespace string
}


func (c *tasksClient) Create(ctx context.Context, task *tektonv1.Task, opts metav1.CreateOptions) (*tektonv1.Task, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewCreateAction(tasksResource, c.Cluster, c.Namespace, task), &tektonv1.Task{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1.Task), err
}

func (c *tasksClient) Update(ctx context.Context, task *tektonv1.Task, opts metav1.UpdateOptions) (*tektonv1.Task, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateAction(tasksResource, c.Cluster, c.Namespace, task), &tektonv1.Task{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1.Task), err
}

func (c *tasksClient) UpdateStatus(ctx context.Context, task *tektonv1.Task, opts metav1.UpdateOptions) (*tektonv1.Task, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateSubresourceAction(tasksResource, c.Cluster, "status", c.Namespace, task), &tektonv1.Task{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1.Task), err
}

func (c *tasksClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewDeleteActionWithOptions(tasksResource, c.Cluster, c.Namespace, name, opts), &tektonv1.Task{})
	return err
}

func (c *tasksClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewDeleteCollectionAction(tasksResource, c.Cluster, c.Namespace, listOpts)

	_, err := c.Fake.Invokes(action, &tektonv1.TaskList{})
	return err
}

func (c *tasksClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*tektonv1.Task, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewGetAction(tasksResource, c.Cluster, c.Namespace, name), &tektonv1.Task{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1.Task), err
}

// List takes label and field selectors, and returns the list of Tasks that match those selectors.
func (c *tasksClient) List(ctx context.Context, opts metav1.ListOptions) (*tektonv1.TaskList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(tasksResource, tasksKind, c.Cluster, c.Namespace, opts), &tektonv1.TaskList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tektonv1.TaskList{ListMeta: obj.(*tektonv1.TaskList).ListMeta}
	for _, item := range obj.(*tektonv1.TaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *tasksClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(tasksResource, c.Cluster, c.Namespace, opts))
}

func (c *tasksClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*tektonv1.Task, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(tasksResource, c.Cluster, c.Namespace, name, pt, data, subresources...), &tektonv1.Task{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1.Task), err
}
