/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	kcpcache "github.com/kcp-dev/apimachinery/pkg/cache"	
	"github.com/kcp-dev/logicalcluster/v2"
	
	"k8s.io/client-go/tools/cache"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/api/errors"
	
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	tektonv1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	tektonv1beta1listers "github.com/tektoncd/pipeline/pkg/client/listers/pipeline/v1beta1"
	)

// PipelineRunClusterLister can list PipelineRuns across all workspaces, or scope down to a PipelineRunLister for one workspace.
type PipelineRunClusterLister interface {
	List(selector labels.Selector) (ret []*tektonv1beta1.PipelineRun, err error)
Cluster(cluster logicalcluster.Name)tektonv1beta1listers.PipelineRunLister
}

type pipelineRunClusterLister struct {
	indexer cache.Indexer
}

// NewPipelineRunClusterLister returns a new PipelineRunClusterLister.
func NewPipelineRunClusterLister(indexer cache.Indexer) *pipelineRunClusterLister {
	return &pipelineRunClusterLister{indexer: indexer}
}

// List lists all PipelineRuns in the indexer across all workspaces.
func (s *pipelineRunClusterLister) List(selector labels.Selector) (ret []*tektonv1beta1.PipelineRun, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*tektonv1beta1.PipelineRun))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get PipelineRuns.
func (s *pipelineRunClusterLister) Cluster(cluster logicalcluster.Name)tektonv1beta1listers.PipelineRunLister {
return &pipelineRunLister{indexer: s.indexer, cluster: cluster}
}

// pipelineRunLister implements the tektonv1beta1listers.PipelineRunLister interface.
type pipelineRunLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all PipelineRuns in the indexer for a workspace.
func (s *pipelineRunLister) List(selector labels.Selector) (ret []*tektonv1beta1.PipelineRun, err error) {
	selectAll := selector == nil || selector.Empty()

	list, err := s.indexer.ByIndex(kcpcache.ClusterIndexName, kcpcache.ClusterIndexKey(s.cluster))
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*tektonv1beta1.PipelineRun)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// PipelineRuns returns an object that can list and get PipelineRuns in one namespace.
func (s *pipelineRunLister) PipelineRuns(namespace string) tektonv1beta1listers.PipelineRunNamespaceLister {
return &pipelineRunNamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// pipelineRunNamespaceLister implements the tektonv1beta1listers.PipelineRunNamespaceLister interface.
type pipelineRunNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all PipelineRuns in the indexer for a given workspace and namespace.
func (s *pipelineRunNamespaceLister) List(selector labels.Selector) (ret []*tektonv1beta1.PipelineRun, err error) {
	selectAll := selector == nil || selector.Empty()

	var list []interface{}
	if s.namespace == metav1.NamespaceAll {
		list, err = s.indexer.ByIndex(kcpcache.ClusterIndexName, kcpcache.ClusterIndexKey(s.cluster))
	} else {
		list, err = s.indexer.ByIndex(kcpcache.ClusterAndNamespaceIndexName, kcpcache.ClusterAndNamespaceIndexKey(s.cluster, s.namespace))
	}
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*tektonv1beta1.PipelineRun)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the PipelineRun from the indexer for a given workspace, namespace and name.
func (s *pipelineRunNamespaceLister) Get(name string) (*tektonv1beta1.PipelineRun, error) {
	key := kcpcache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tektonv1beta1.Resource("PipelineRun"), name)
	}
	return obj.(*tektonv1beta1.PipelineRun), nil
}
