/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"github.com/kcp-dev/logicalcluster/v2"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	tektonv1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"

	"k8s.io/apimachinery/pkg/watch"

	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/types"

	kcptektonv1beta1 "github.com/tektoncd/pipeline/pkg/client/cluster/clientset/typed/tekton/v1beta1"

	tektonv1beta1client "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/typed/pipeline/v1beta1"
)

var pipelineRunsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1beta1", Resource: "pipelineruns"}
var pipelineRunsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1beta1", Kind: "PipelineRun"}

type pipelineRunsClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *pipelineRunsClusterClient) Cluster(cluster logicalcluster.Name) kcptektonv1beta1.PipelineRunsNamespacer {
	if cluster == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &pipelineRunsNamespacer{Fake: c.Fake, Cluster: cluster}
}


// List takes label and field selectors, and returns the list of PipelineRuns that match those selectors across all clusters.
func (c *pipelineRunsClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*tektonv1beta1.PipelineRunList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(pipelineRunsResource, pipelineRunsKind, logicalcluster.Wildcard, metav1.NamespaceAll, opts), &tektonv1beta1.PipelineRunList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tektonv1beta1.PipelineRunList{ListMeta: obj.(*tektonv1beta1.PipelineRunList).ListMeta}
	for _, item := range obj.(*tektonv1beta1.PipelineRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested PipelineRuns across all clusters.
func (c *pipelineRunsClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(pipelineRunsResource, logicalcluster.Wildcard, metav1.NamespaceAll, opts))
}
type pipelineRunsNamespacer struct {
	*kcptesting.Fake
	Cluster logicalcluster.Name
}

func (n *pipelineRunsNamespacer) Namespace(namespace string) tektonv1beta1client.PipelineRunInterface {
	return &pipelineRunsClient{Fake: n.Fake, Cluster: n.Cluster, Namespace: namespace}
}
type pipelineRunsClient struct {
	*kcptesting.Fake
	Cluster logicalcluster.Name
	Namespace string
}


func (c *pipelineRunsClient) Create(ctx context.Context, pipelineRun *tektonv1beta1.PipelineRun, opts metav1.CreateOptions) (*tektonv1beta1.PipelineRun, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewCreateAction(pipelineRunsResource, c.Cluster, c.Namespace, pipelineRun), &tektonv1beta1.PipelineRun{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1beta1.PipelineRun), err
}

func (c *pipelineRunsClient) Update(ctx context.Context, pipelineRun *tektonv1beta1.PipelineRun, opts metav1.UpdateOptions) (*tektonv1beta1.PipelineRun, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateAction(pipelineRunsResource, c.Cluster, c.Namespace, pipelineRun), &tektonv1beta1.PipelineRun{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1beta1.PipelineRun), err
}

func (c *pipelineRunsClient) UpdateStatus(ctx context.Context, pipelineRun *tektonv1beta1.PipelineRun, opts metav1.UpdateOptions) (*tektonv1beta1.PipelineRun, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateSubresourceAction(pipelineRunsResource, c.Cluster, "status", c.Namespace, pipelineRun), &tektonv1beta1.PipelineRun{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1beta1.PipelineRun), err
}

func (c *pipelineRunsClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewDeleteActionWithOptions(pipelineRunsResource, c.Cluster, c.Namespace, name, opts), &tektonv1beta1.PipelineRun{})
	return err
}

func (c *pipelineRunsClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewDeleteCollectionAction(pipelineRunsResource, c.Cluster, c.Namespace, listOpts)

	_, err := c.Fake.Invokes(action, &tektonv1beta1.PipelineRunList{})
	return err
}

func (c *pipelineRunsClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*tektonv1beta1.PipelineRun, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewGetAction(pipelineRunsResource, c.Cluster, c.Namespace, name), &tektonv1beta1.PipelineRun{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1beta1.PipelineRun), err
}

// List takes label and field selectors, and returns the list of PipelineRuns that match those selectors.
func (c *pipelineRunsClient) List(ctx context.Context, opts metav1.ListOptions) (*tektonv1beta1.PipelineRunList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(pipelineRunsResource, pipelineRunsKind, c.Cluster, c.Namespace, opts), &tektonv1beta1.PipelineRunList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tektonv1beta1.PipelineRunList{ListMeta: obj.(*tektonv1beta1.PipelineRunList).ListMeta}
	for _, item := range obj.(*tektonv1beta1.PipelineRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *pipelineRunsClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(pipelineRunsResource, c.Cluster, c.Namespace, opts))
}

func (c *pipelineRunsClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*tektonv1beta1.PipelineRun, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(pipelineRunsResource, c.Cluster, c.Namespace, name, pt, data, subresources...), &tektonv1beta1.PipelineRun{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tektonv1beta1.PipelineRun), err
}
