/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v2"

	tektonv1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	tektonv1listers "github.com/tektoncd/pipeline/pkg/client/cluster/listers/tekton/v1"
	upstreamtektonv1listers "github.com/tektoncd/pipeline/pkg/client/listers/pipeline/v1"
	upstreamtektonv1informers "github.com/tektoncd/pipeline/pkg/client/informers/externalversions/pipeline/v1"
	clientset "github.com/tektoncd/pipeline/pkg/client/cluster/clientset"

	"github.com/tektoncd/pipeline/pkg/client/cluster/informers/internalinterfaces"
)

// TaskClusterInformer provides access to a shared informer and lister for
// Tasks.
type TaskClusterInformer interface {
	Cluster(logicalcluster.Name) upstreamtektonv1informers.TaskInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() tektonv1listers.TaskClusterLister
}

type taskClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTaskClusterInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTaskClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredTaskClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredTaskClusterInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTaskClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TektonV1().Tasks().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TektonV1().Tasks().Watch(context.TODO(), options)
			},
		},
		&tektonv1.Task{},
		resyncPeriod,
		indexers,
	)
}

func (f *taskClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredTaskClusterInformer(client, resyncPeriod, cache.Indexers{
			kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
			kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,}, 
		f.tweakListOptions,
	)
}

func (f *taskClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&tektonv1.Task{}, f.defaultInformer)
}

func (f *taskClusterInformer) Lister() tektonv1listers.TaskClusterLister {
	return tektonv1listers.NewTaskClusterLister(f.Informer().GetIndexer())
}

func (f *taskClusterInformer) Cluster(cluster logicalcluster.Name) upstreamtektonv1informers.TaskInformer {
	return &taskInformer{
		informer: f.Informer().Cluster(cluster),
		lister:   f.Lister().Cluster(cluster),
	}
}

type taskInformer struct {
	informer cache.SharedIndexInformer
	lister upstreamtektonv1listers.TaskLister
}

func (f *taskInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *taskInformer) Lister() upstreamtektonv1listers.TaskLister {
	return f.lister
}
