/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	resolutionv1beta1 "github.com/tektoncd/pipeline/pkg/apis/resolution/v1beta1"


	resolutionv1beta1client "github.com/tektoncd/pipeline/pkg/client/resolution/clientset/versioned/typed/resolution/v1beta1"
)

// ResolutionRequestsClusterGetter has a method to return a ResolutionRequestClusterInterface.
// A group's cluster client should implement this interface.
type ResolutionRequestsClusterGetter interface {
	ResolutionRequests() ResolutionRequestClusterInterface
}

// ResolutionRequestClusterInterface can operate on ResolutionRequests across all clusters,
// or scope down to one cluster and return a ResolutionRequestsNamespacer.
type ResolutionRequestClusterInterface interface {
	Cluster(logicalcluster.Name) ResolutionRequestsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*resolutionv1beta1.ResolutionRequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type resolutionRequestsClusterInterface struct {
	clientCache kcpclient.Cache[*resolutionv1beta1client.ResolutionV1beta1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *resolutionRequestsClusterInterface) Cluster(name logicalcluster.Name) ResolutionRequestsNamespacer {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &resolutionRequestsNamespacer{clientCache: c.clientCache, name: name}
}


// List returns the entire collection of all ResolutionRequests across all clusters. 
func (c *resolutionRequestsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*resolutionv1beta1.ResolutionRequestList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResolutionRequests(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all ResolutionRequests across all clusters.
func (c *resolutionRequestsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResolutionRequests(metav1.NamespaceAll).Watch(ctx, opts)
}
// ResolutionRequestsNamespacer can scope to objects within a namespace, returning a resolutionv1beta1client.ResolutionRequestInterface.
type ResolutionRequestsNamespacer interface {
	Namespace(string) resolutionv1beta1client.ResolutionRequestInterface
}

type resolutionRequestsNamespacer struct {
	clientCache kcpclient.Cache[*resolutionv1beta1client.ResolutionV1beta1Client]
	name logicalcluster.Name
}

func (n *resolutionRequestsNamespacer) Namespace(namespace string) resolutionv1beta1client.ResolutionRequestInterface {
	return n.clientCache.ClusterOrDie(n.name).ResolutionRequests(namespace)
}
